'use client'

import { useCallback, useEffect, useMemo, useState } from 'react'
import { AlertTriangle, Cloud, CloudDrizzle, CloudRain, Droplets, Gauge, Home, MapPin, Moon, Navigation, RefreshCw, Sun, Umbrella, Wind, CircleHelp, LayoutGrid, Bell, MessageCircle, Send } from 'lucide-react'

const API_URL = 'https://data.weather.gov.hk/weatherAPI/opendata/weather.php?dataType=rhrread&lang=en'
const districts = [
  { name: 'Central & Western', temp: 28, rain: 35, note: 'Light showers' },
  { name: 'Wan Chai', temp: 29, rain: 42, note: 'Passing rain' },
  { name: 'Kowloon City', temp: 30, rain: 28, note: 'Mostly cloudy' },
  { name: 'Sha Tin', temp: 27, rain: 55, note: 'Scattered showers' },
  { name: 'Sai Kung', temp: 26, rain: 68, note: 'Rain likely' },
]
type WeatherData = { temperature?: { data?: Array<{ place: string; value: number }> }; humidity?: { data?: Array<{ value: number }> }; wind?: { data?: Array<{ speed: number }> }; warningMessage?: string[]; updateTime?: string }
type Tab = 'home' | 'compare' | 'alerts' | 'qa' | 'chat'
type WeatherSource = { label: string; url: string; updatedAt: string | null; status: string }
type ChatMessage = { role: 'user' | 'assistant'; content: string; weatherSources?: WeatherSource[] }

function formatUpdated(value?: string) { if (!value) return 'Waiting for live data'; const date = new Date(value); return Number.isNaN(date.getTime()) ? value.replace('T', ' ').replace('+08:00', '') : `Updated ${date.toLocaleTimeString('en-HK', { hour: '2-digit', minute: '2-digit' })}` }
function weatherIcon(rain: number) { return rain > 60 ? <CloudRain aria-hidden="true" /> : rain > 30 ? <CloudDrizzle aria-hidden="true" /> : <Cloud aria-hidden="true" /> }

export default function HomePage() {
  const [tab, setTab] = useState<Tab>('home')
  const [data, setData] = useState<WeatherData | null>(null)
  const [selected, setSelected] = useState(districts[0].name)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [lastFetched, setLastFetched] = useState<Date | null>(null)
  const [dark, setDark] = useState(false)

  useEffect(() => { const saved = window.localStorage.getItem('hk-weather-theme'); const prefers = window.matchMedia('(prefers-color-scheme: dark)').matches; setDark(saved ? saved === 'dark' : prefers) }, [])
  useEffect(() => { document.documentElement.classList.toggle('dark', dark); window.localStorage.setItem('hk-weather-theme', dark ? 'dark' : 'light') }, [dark])
  const fetchWeather = useCallback(async () => { setLoading(true); setError(''); try { const response = await fetch(API_URL, { cache: 'no-store' }); if (!response.ok) throw new Error(); setData(await response.json() as WeatherData); setLastFetched(new Date()) } catch { setError('Unable to connect to the Hong Kong Observatory. Showing the latest available view.') } finally { setLoading(false) } }, [])
  useEffect(() => { fetchWeather() }, [fetchWeather])
  const centralTemp = data?.temperature?.data?.find((item) => item.place === 'Hong Kong Observatory')?.value ?? 28
  const humidity = data?.humidity?.data?.[0]?.value ?? 78
  const wind = data?.wind?.data?.[0]?.speed ?? 12
  const warnings = useMemo(() => { const raw = data?.warningMessage; return Array.isArray(raw) ? raw.filter(Boolean) : typeof raw === 'string' && raw ? [raw] : [] }, [data])
  const selectedDistrict = districts.find((item) => item.name === selected) ?? districts[0]

  return <main className="min-h-screen bg-background text-foreground"><div className="weather-grid pointer-events-none fixed inset-0 -z-0 opacity-60" /><div className="relative z-10 mx-auto max-w-5xl px-4 pb-24 pt-4 sm:px-8">
    <header className="flex items-center justify-between border-b border-border/70 pb-4"><button className="flex items-center gap-2.5 text-left" onClick={() => setTab('home')} aria-label="Go to Home"><span className="brand-mark"><Cloud size={19} aria-hidden="true" /></span><span><span className="block font-mono text-[10px] font-semibold uppercase tracking-[0.22em] text-primary">HK WEATHER</span><span className="block text-[11px] text-muted-foreground">Live conditions, citywide</span></span></button><div className="flex items-center gap-2"><button className="theme-button" onClick={() => setDark((value) => !value)} aria-label={`Switch to ${dark ? 'light' : 'dark'} mode`} title={`Switch to ${dark ? 'light' : 'dark'} mode`}>{dark ? <Sun size={16} /> : <Moon size={16} />}</button><button className="refresh-button" onClick={fetchWeather} disabled={loading} aria-label="Refresh weather data"><RefreshCw size={15} className={loading ? 'animate-spin' : ''} /><span className="hidden sm:inline">Refresh</span></button></div></header>
    {error && <div className="mt-4 flex gap-2 border border-warning/30 bg-warning/10 px-3 py-2.5 text-xs text-warning"><AlertTriangle size={15} />{error}</div>}
    <div className="mt-6">{tab === 'home' && <HomeTab temp={centralTemp} humidity={humidity} wind={wind} updated={lastFetched ? formatUpdated(lastFetched.toISOString()) : 'Live feed'} loading={loading} updateTime={data?.updateTime} onCompare={() => setTab('compare')} onAlerts={() => setTab('alerts')} />}{tab === 'compare' && <CompareTab selected={selected} setSelected={setSelected} selectedDistrict={selectedDistrict} />}{tab === 'alerts' && <AlertsTab warnings={warnings} updateTime={data?.updateTime} />}{tab === 'qa' && <QATab onHome={() => setTab('home')} />}{tab === 'chat' && <ChatTab />}</div>
  </div><BottomNav tab={tab} setTab={setTab} /></main>
}

function HomeTab({ temp, humidity, wind, updated, loading, updateTime, onCompare, onAlerts }: { temp: number; humidity: number; wind: number; updated: string; loading: boolean; updateTime?: string; onCompare: () => void; onAlerts: () => void }) { return <><section className="hero-section pb-7 pt-3"><p className="eyebrow"><span className="live-dot" /> Hong Kong · {updated}</p><h1 className="mt-3 text-balance text-[2.65rem] font-semibold leading-[.98] tracking-[-0.07em] sm:text-6xl">Know before you<br /><span className="text-primary">step outside.</span></h1><p className="mt-4 max-w-xl text-pretty text-sm leading-6 text-muted-foreground">A clear view of what&apos;s happening across the city, from your morning commute to tonight&apos;s plans.</p></section><section className="dashboard-card overflow-hidden"><div className="p-5 sm:p-8"><div className="flex items-center gap-2 text-sm text-muted-foreground"><MapPin size={15} className="text-primary" /> Hong Kong Observatory</div><div className="mt-5 flex items-end justify-between gap-3"><div className="flex items-end gap-3"><span className="temperature">{temp}°</span><div className="pb-1"><p className="text-base font-medium">Mostly cloudy</p><p className="text-xs text-muted-foreground">Feels like {temp + 2}°</p></div></div><div className="weather-icon-large"><Cloud size={55} strokeWidth={1.3} /></div></div><div className="mt-6 grid grid-cols-2 gap-4 border-t border-border pt-5 sm:grid-cols-4"><Metric icon={<Droplets />} label="Humidity" value={`${humidity}%`} /><Metric icon={<Wind />} label="Wind" value={`${wind} km/h`} /><Metric icon={<Umbrella />} label="Rain chance" value="40%" /><Metric icon={<Gauge />} label="Visibility" value="10 km" /></div></div><div className="flex items-center justify-between border-t border-border bg-secondary/50 px-5 py-2.5 text-[10px] text-muted-foreground sm:px-8"><span>Source: Hong Kong Observatory</span><span>{loading ? 'Updating…' : formatUpdated(updateTime)}</span></div></section><div className="mt-5 grid gap-3 sm:grid-cols-2"><button className="quick-link" onClick={onCompare}><LayoutGrid size={18} /><span><b>Compare locations</b><small>See conditions across the city</small></span><span>→</span></button><button className="quick-link" onClick={onAlerts}><Bell size={18} /><span><b>Weather warnings</b><small>Stay ahead of changing conditions</small></span><span>→</span></button></div></> }
function CompareTab({ selected, setSelected, selectedDistrict }: { selected: string; setSelected: (value: string) => void; selectedDistrict: typeof districts[number] }) { return <PageIntro eyebrow="Across the city" title="Compare locations" description="Check conditions in the places you are headed." ><div className="section-panel"><div className="location-list">{districts.map((district) => <button key={district.name} className={`location-row ${selected === district.name ? 'selected' : ''}`} onClick={() => setSelected(district.name)} aria-pressed={selected === district.name}><span className="location-weather-icon">{weatherIcon(district.rain)}</span><span className="min-w-0 flex-1 text-left"><span className="block truncate font-medium">{district.name}</span><span className="block text-xs text-muted-foreground">{district.note}</span></span><span className="mr-3 text-xs text-muted-foreground">{district.rain}%</span><span className="w-9 text-right text-lg font-medium">{district.temp}°</span></button>)}</div><div className="selected-location mt-4"><div><p className="eyebrow text-primary">Selected area</p><p className="mt-1 text-lg font-medium">{selectedDistrict.name}</p><p className="mt-1 text-xs text-muted-foreground">{selectedDistrict.note} · {selectedDistrict.rain}% chance of rain</p></div><Navigation size={25} className="text-primary" /></div></div></PageIntro> }
function AlertsTab({ warnings, updateTime }: { warnings: string[]; updateTime?: string }) { return <PageIntro eyebrow="Stay prepared" title="Weather warnings" description="Official alerts from the Hong Kong Observatory."><div className="section-panel">{warnings.length ? <div className="warning-stack">{warnings.map((warning, index) => <div className="warning-row" key={`${warning}-${index}`}><AlertTriangle size={18} /><p>{warning}</p></div>)}</div> : <div className="all-clear"><div className="clear-icon"><Sun size={24} /></div><p className="font-medium">No active warnings</p><p className="mt-1 text-sm leading-6 text-muted-foreground">The city is clear for now. Alerts will appear here as soon as they&apos;re issued.</p></div>}<div className="mt-6 flex items-center gap-2 border-t border-border pt-4 text-xs text-muted-foreground"><span className="status-dot" /> Monitoring live alerts · {formatUpdated(updateTime)}</div></div></PageIntro> }
function QATab({ onHome }: { onHome: () => void }) { const items = [['What is Hong Kong’s rainy season?', 'The wettest months are typically May through September, with frequent showers and thunderstorms.'], ['When is typhoon season?', 'Tropical cyclone season generally runs from May to November, with the highest activity from July to September.'], ['Why does Hong Kong feel so humid?', 'Warm ocean air and the city’s subtropical climate keep humidity high, especially before rain.'], ['What should I bring on a cloudy day?', 'A compact umbrella is a smart choice. Cloud cover can shift quickly into a passing shower.'], ['Where can I find official warnings?', 'This app mirrors live warnings from the Hong Kong Observatory so you can check before heading out.']]; return <PageIntro eyebrow="Weather, explained" title="Common questions" description="A quick guide to Hong Kong’s changing skies."><div className="qa-list">{items.map(([question, answer]) => <details key={question} className="qa-item"><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div><button className="home-return" onClick={onHome}><Home size={16} /> Return to Home</button></PageIntro> }
function ChatTab() {
  const [messages, setMessages] = useState<ChatMessage[]>([{ role: 'assistant', content: 'Hi, I can help with Hong Kong weather, seasons, rain, typhoons, and planning your day.' }])
  const [input, setInput] = useState('')
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const sendMessage = async () => {
    const content = input.trim()
    if (!content || loading) return
    const nextMessages = [...messages, { role: 'user' as const, content }]
    setMessages(nextMessages); setInput(''); setError(''); setLoading(true)
    try {
      const response = await fetch('/api/chat', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ messages: nextMessages }) })
      const result = await response.json()
      if (!response.ok) throw new Error(result.error || 'Unable to answer right now.')
      setMessages((current) => [...current, { role: 'assistant', content: result.message, weatherSources: result.weatherSources }])
    } catch (chatError) { setError(chatError instanceof Error ? chatError.message : 'Unable to answer right now.') } finally { setLoading(false) }
  }
  return <PageIntro eyebrow="Ask the forecast" title="Weather assistant" description="Ask a practical question about Hong Kong weather."><div className="chat-panel"><div className="chat-history" aria-live="polite">{messages.map((message, index) => <div key={`${message.role}-${index}`} className={`chat-bubble ${message.role}`}><span className="whitespace-pre-wrap">{message.content}</span>{message.weatherSources && <div className="mt-3 border-t border-border pt-2 text-[10px] leading-5 text-muted-foreground"><p>Hong Kong Observatory · 香港天文台</p>{message.weatherSources.map((source) => <div key={source.url}><a href={source.url} target="_blank" rel="noopener noreferrer" className="underline underline-offset-2">{source.label}</a>: {source.status === 'available' && source.updatedAt ? new Date(source.updatedAt).toLocaleString('en-GB', { timeZone: 'Asia/Hong_Kong', dateStyle: 'short', timeStyle: 'short' }) + ' HKT' : 'Unavailable / 暫未取得'}</div>)}</div>}</div>)}{loading && <div className="chat-bubble assistant"><span className="typing-dots" aria-label="Assistant is typing">•••</span></div>}</div>{error && <p className="chat-error" role="alert">{error}</p>}<form className="chat-form" onSubmit={(event) => { event.preventDefault(); void sendMessage() }}><input value={input} onChange={(event) => setInput(event.target.value)} placeholder="e.g. Should I bring an umbrella?" aria-label="Ask a Hong Kong weather question" disabled={loading} /><button type="submit" aria-label="Send question" disabled={loading || !input.trim()}><Send size={16} /></button></form><p className="chat-note">Uses the latest available HKO observations, forecast and warnings. Source times are shown in Hong Kong time.</p></div></PageIntro>
}

function PageIntro({ eyebrow, title, description, children }: { eyebrow: string; title: string; description: string; children: React.ReactNode }) { return <section><div className="mb-6"><p className="eyebrow"><CircleHelp size={13} /> {eyebrow}</p><h1 className="mt-3 text-4xl font-semibold tracking-[-0.06em]">{title}</h1><p className="mt-3 text-sm leading-6 text-muted-foreground">{description}</p></div>{children}</section> }
function BottomNav({ tab, setTab }: { tab: Tab; setTab: (value: Tab) => void }) { const items: [Tab, string, React.ReactNode][] = [['home', 'Home', <Home key="home" />], ['compare', 'Compare', <LayoutGrid key="compare" />], ['alerts', 'Alerts', <Bell key="alerts" />], ['qa', 'Q&A', <CircleHelp key="qa" />], ['chat', 'Chat', <MessageCircle key="chat" />]]; return <nav className="bottom-nav" aria-label="Main navigation">{items.map(([id, label, icon]) => <button key={id} className={tab === id ? 'active' : ''} onClick={() => setTab(id)} aria-current={tab === id ? 'page' : undefined}>{icon}<span>{label}</span></button>)}</nav> }
function Metric({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div><div className="mb-1.5 flex items-center gap-1.5 text-muted-foreground [&_svg]:size-3.5">{icon}<span className="text-[11px]">{label}</span></div><p className="text-sm font-medium">{value}</p></div> }
